default :
  adapter: mysql2
  database: shopping_api
  username: anitawright
  password: preeti
  host: localhost

development :
  adapter: mysql2
  database: shopping_api
  username: anitawright
  password: preeti
  host: localhost

production :
  adapter: mysql2
  database: shopping_api
  username: anitawright
  password: preeti
  host: localhost
